---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
    name: kata-nvidia-gpu
handler: kata-nvidia-gpu
overhead:
    podFixed:
        memory: "160Mi"
        cpu: "250m"
scheduling:
  nodeSelector:
    node-role.kubernetes.io/master: ""
