---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
    name: kata-nvidia-gpu-cc
handler: kata-nvidia-gpu-snp
overhead:
    podFixed:
        memory: "2048Mi"
        cpu: "1.0"
scheduling:
  nodeSelector:
    node-role.kubernetes.io/master: ""
